# Configuraci贸n para el proyecto agent-general

# Modo debug (True/False)
debug: True

# Nivel de log (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_level: INFO

# Configuraci贸n de proveedores
providers:
  # Configuraci贸n para OpenAI
  openai:
    model: gpt-4o
    max_tokens: 150
    temperature: 0.7
  
  # Configuraci贸n para Claude
  claude:
    enabled: False
